### ISSUE TITLE
Remove styled-components and layout-styled-components from dependencies

### ISSUE THREAD

**Issue by kitze** [kitze/react-genie#11]
Maybe even `react-animations` can be a separate package if the structure is changed.

**Comment by lmuller18** [comment]
Since `layout-styled-components` is being used for flex styling on the animated title component, what would you like to use instead if it was removed as a dep? style props, css, scss, etc?

**Comment by kitze** [comment]
@lmuller18 inline styles should be enough for adding flex properties and margin for the words

**Comment by yo7** [comment]
When I import `react-genie` I get the error: `Module not found: Can't resolve 'layout-styled-components'`.
And it seems [demo](https://codesandbox.io/s/react-genie-example-8xfsc) also has the same error.
