### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by aichbauer** [kitze/react-genie#6]
Currently only the example is licensed under the `MIT License`.

<img width="1176" alt="Screenshot 2019-10-02 at 21 42 45" src="https://user-images.githubusercontent.com/14862422/66076272-bac98900-e55d-11e9-93d8-6da281088e1b.png">

I am not saying that you have to license it under the `MIT License` but any kind of license would help to decide whether you can use this package in your project or not. Specially if you want to use it on a project that has been published or will be in future. 

I find this project really useful. Keep up the good work 👍

**Comment by kitze** [comment]
Hey @aichbauer, glad you like the lib. I just added the MIT license 👍️
